#ifndef FUNCONFIG_H_
#define FUNCONFIG_H_

#define CH32V003           1
#undef FUNCONF_USE_UARTPRINTF

#define SYSTEM_CORE_CLOCK 24000000
#define APB_CLOCK SYSTEM_CORE_CLOCK

#define FUNCONF_UART_PRINTF_BAUD 115200
#define UART_PINS_TXPD5_RXPD6
#define CH32V003_UART_IMPLEMENTATION

#endif
